<?php include('views/shared/header/header.phtml'); ?>

<?php
session_start(); // Asegúrate de iniciar la sesión al inicio del archivo

// Obtener el mensaje de la sesión
$message = isset($_SESSION['message']) ? $_SESSION['message'] : '';
$messageType = isset($_SESSION['message_type']) ? $_SESSION['message_type'] : '';

// Limpiar el mensaje de la sesión después de mostrarlo
unset($_SESSION['message']);
unset($_SESSION['message_type']);
?>

<!-- Mostrar el popup si hay un mensaje -->
<?php if ($message): ?>
    <div id="popupMessage" class="popup <?php echo htmlspecialchars($messageType); ?>">
        <?php echo htmlspecialchars($message); ?>
    </div>
<?php endif; ?>
<main>
<center><h2>Login</h2></center>
<center><h4>usuario:jona  Contraseña:123456</h4></center>
    <div class="container">
        <form id="pacienteForm" action="/login/access" method="post">
            <div class="mb-3">
                <label for="usuario" class="form-label">usuario</label>
                <input type="text" class="form-control" name="usuario" id="usuario" aria-describedby="nomdesc">
                <div id="nomdesc" class="form-text">Escribir tu usuario</div>
            </div>
            <div class="mb-3">
                <label for="pass" class="form-label">Contraseña</label>
                <input  type="password" class="form-control" id="pass" name="pass" require>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>

</main>
<?php include('views/shared/footer/footer.phtml'); ?>