<?php include('views/shared/header/header.phtml');
?>
<main>
    <?php
    session_start(); // Asegúrate de iniciar la sesión al inicio del archivo

    $log = isset($_SESSION['log']) ? $_SESSION['log'] : ''; // sesión loggin 
    if (empty($log)) {
        echo "Error";
    }


    // Obtener el mensaje de la sesión
    $message = isset($_SESSION['message']) ? $_SESSION['message'] : '';
    $messageType = isset($_SESSION['message_type']) ? $_SESSION['message_type'] : '';

    // Limpiar el mensaje de la sesión después de mostrarlo
    unset($_SESSION['message']);
    unset($_SESSION['message_type']);
    ?>

    <!-- Mostrar el popup si hay un mensaje -->
    <?php if ($message): ?>
        <div id="popupMessage" class="popup <?php echo htmlspecialchars($messageType); ?>">
            <?php echo htmlspecialchars($message); ?>
        </div>
    <?php endif; ?>

    <div class="container mt-5">
        <h1 class="mb-4">Vista de Consultas</h1>

        <!-- Crear la tabla con Bootstrap -->
        <table class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>Dia</th>
                    <th>Coonsultas</th>
                    <th>Total</th>
                </tr>
            </thead>


            <tbody>
                <?php
                // Recorrer el arreglo de datos y generar las filas de la tabla
                foreach ($data as $fila) {
                    echo '<tr>' . '<td><strong>' . htmlspecialchars($fila['fecha_consulta']) . '</strong></td><td></td><td></td>' . '</tr>';
                    echo '<tr>';
                    echo '<td>' . htmlspecialchars($fila['nombre_usuario']) . '</td>';
                    echo '<td>' . htmlspecialchars($fila['CONSULTAS']) . '</td>';
                    echo '<td>' . htmlspecialchars($fila['total_costo']) . '</td>';
                    echo '</tr>';
                }
                ?>
            </tbody>
        </table>
    </div>

    <form method="post" action="/library/export_xlsx.php">
        <button type="submit" name="export_xlsx" class="btn btn-success">Exportar a XLSX</button>
    </form>
</main>
<!-- <script>
    // Mostrar el popup si hay un mensaje
    window.onload = function() {
        var popup = document.getElementById('popupMessage');
        if (popup) {
            popup.style.display = 'block';
            // Ocultar el popup después de 3 segundos
            setTimeout(function() {
                popup.style.display = 'none';
            }, 3000);
        }
    };
</script> -->
<?php include('views/shared/footer/footer.phtml'); ?>